# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

project 'CovidApp - Covid Community Alert.xcodeproj'
source 'https://github.com/CocoaPods/Specs.git'

target 'CovidApp - Covid Community Alert' do

  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for CovidApp - Covid Community Alert
  pod "ReCaptcha/RxSwift"
end
